const resList = [
    {
      data: {
        id: "446303",
        name: "Third Wave Coffee",
        cloudinaryImageId: "0dca660dbdf2e04f9b861c4426ffd41e",
        cuisines: ["Beverages", "Bakery", "Continental"],
        tags: [],
        costForTwo: 40000,
        deliveryTime: 23,
        avgRating: "4.5",
      }
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "89598",
        name: "The Hunger Home",
        uuid: "f1a9ac02-1155-4f89-a183-a44808860ffb",
        city: "4",
        area: "East of Kailash",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "b743dm8wyqjcta3tvffk",
        cuisines: ["Chinese", "North Indian", "Continental", "Beverages"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        slaString: "19 MINS",
        lastMileTravel: 0.699999988079071,
        slugs: {
          restaurant: "the-hunger-home-east-of-kailash-greater-kailash-2",
          city: "delhi",
        },
        cityState: "4",
        address:
          "D - 8,1st floor DDA Market Adjacent To Wine Shop East Of kailash, NEW DELHI -110065",
        locality: "Raja Dhirsain Marg",
        parentId: 15631,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "89598",
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          lastMileTravel: 0.699999988079071,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "40315",
        name: "Moolchand Parantha",
        uuid: "fd02d1ce-d4ed-43ea-91fb-77de3254a580",
        city: "4",
        area: "Kalkaji",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "kv0p20lqiir6abfve0x2",
        cuisines: ["North Indian", "Snacks", "Chinese"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: "23 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "moolchand-parantha-kalkaji-greater-kailash-2",
          city: "delhi",
        },
        cityState: "4",
        address:
          "Shop 3, Opposite Deshbandhu College, Krishna Market, Kalkaji, New Delhi",
        locality: "Deshbandu College Road",
        parentId: 272127,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4600,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4600,
          message: "",
          title: "Delivery Charge",
          amount: "4600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "40315",
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "619256",
        name: "Food_O_Gasm",
        uuid: "5f9113af-d81a-496e-b376-3cdaa2d65a7a",
        city: "4",
        area: "Lajpat Nagar 4",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "c40624dc0b1288c480a4ae049d9c8634",
        cuisines: ["North Indian", "Nepalese", "Chinese", "Italian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 1.7000000476837158,
        slugs: {
          restaurant: "food_o_gasm-lajpat-nagar-lajpat-nagar",
          city: "delhi",
        },
        cityState: "4",
        address:
          "5/3, OLD DOUBLE STOREY, LAJPAT NAGAR- IV, SOUTH DELHI, DELHI-110024,  KILOKARI, DEFENCE COLONY, South East, Delhi - 110024",
        locality: "Kilokari",
        parentId: 368969,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6830262~p=4~eid=00000188-8cfe-0c45-015e-557e00bd0407",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "ABOVE ₹700",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "619256",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 1.7000000476837158,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.8",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "234095",
        name: "McDonald's",
        uuid: "2b82058c-b5ae-4e75-8985-d08877a19c5c",
        city: "4",
        area: "Nehru Place",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "08eee882fda81b68e5c36e3a5d89d8c0",
        cuisines: ["American"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 2,
        slugs: {
          restaurant: "mcdonalds-saytam-cinema-complex-greater-kailash-2",
          city: "delhi",
        },
        cityState: "4",
        address:
          "Delhi Nehru Place, Shop No. 01, Plot No. 45 Saytam Cinema Complex, Nehru Place. New Delhi- 110019",
        locality: "Saytam Cinema Complex",
        parentId: 630,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "234095",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 2,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "54499",
        name: "Pasta La Vista",
        uuid: "2d2d72ba-a77b-4e9c-a188-4553f42f8d11",
        city: "4",
        area: "East of Kailash",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "bnqjo4agsotum9e5siv6",
        cuisines: ["Italian", "Pizzas", "American"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 18,
        minDeliveryTime: 18,
        maxDeliveryTime: 18,
        slaString: "18 MINS",
        lastMileTravel: 0.10000000149011612,
        slugs: {
          restaurant: "pasta-la-vista-sant-nagar-greater-kailash-2",
          city: "delhi",
        },
        cityState: "4",
        address: "333, Shop no.2, Sant Nagar ,East of Kailash",
        locality: "Sant Nagar",
        parentId: 2372,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "54499",
          deliveryTime: 18,
          minDeliveryTime: 18,
          maxDeliveryTime: 18,
          lastMileTravel: 0.10000000149011612,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "54795",
        name: "Yangkiez by Momo Mami",
        uuid: "4e91383d-cd57-4593-96b9-fff9eb8d0943",
        city: "4",
        area: "Lala Lajpat Rai Marg",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "e63dda1eacebdfc79b28df1b8aac104e",
        cuisines: ["Chinese", "Pan-Asian", "Tibetan"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 2.5,
        slugs: {
          restaurant: "yangkiez-malviya-malviya-nagar",
          city: "delhi",
        },
        cityState: "4",
        address: "Second floor, property number118A zamrudpur New Delhi 110048",
        locality: "Zamrudpur",
        parentId: 227486,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "Closes soon",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=7030431~p=7~eid=00000188-8cfe-0c45-015e-557f00bd0740",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "54795",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 2.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "93958",
        name: "The Burger Club",
        uuid: "69e357bc-f3f1-43f4-a803-775ba1a06a1a",
        city: "4",
        area: "Lajpat Nagar 2",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "zucdrsrvvjsz1blwoykx",
        cuisines: ["American", "Beverages", "Desserts"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "the-burger-club-lajpat-nagar-2-lajpat-nagar",
          city: "delhi",
        },
        cityState: "4",
        address: "E-3 first floor lajpat nagar 2",
        locality: "E Block",
        parentId: 2285,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 4600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4600,
          message: "",
          title: "Delivery Charge",
          amount: "4600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "93958",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "3563",
        name: "Hot Paprika",
        uuid: "9437195b-2c50-4ce6-a00e-f3ffdabc6414",
        city: "4",
        area: "East of Kailash",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "js7abefydjchclxnwidr",
        cuisines: ["Chinese", "Snacks", "North Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: "20 MINS",
        lastMileTravel: 0.699999988079071,
        slugs: {
          restaurant: "hot-paprika-south-delhi",
          city: "delhi",
        },
        cityState: "4",
        address:
          "D - 8,1st floor DDA Market Adjacent To Wine Shop East Of kailash, NEW DELHI -110065",
        locality: "Raja Dhirsain Marg",
        parentId: 1413,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "3563",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 0.699999988079071,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.7",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "417312",
        name: "NOTO - Healthy Ice Cream",
        uuid: "6502c2da-a0fb-4fee-beca-12aa63d58078",
        city: "4",
        area: "Lajpat Nagar 2",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "51bd9c7efcc0e05c614c0e0674434e62",
        cuisines: ["Ice Cream"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 3.799999952316284,
        slugs: {
          restaurant: "noto---healthy-ice-cream-lajpat-nagar-lajpat-nagar",
          city: "delhi",
        },
        cityState: "4",
        address:
          "D 72 LAJPAT NAGAR, BAHA PUR, KALKAJI, South East, Delhi - 110024",
        locality: "Lajpat Nagar",
        parentId: 7158,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 4600,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4600,
          message: "",
          title: "Delivery Charge",
          amount: "4600",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=7042039~p=10~eid=00000188-8cfe-0c45-015e-558000bd0a73",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.7 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "417312",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 3.799999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.5",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "449339",
        name: "Chinese Hut",
        uuid: "02374a81-7db7-4772-8f1a-bed47f87c1d1",
        city: "4",
        area: "Lajpat Nagar 4",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "mefiqdmw2mfyhxmgnsun",
        cuisines: ["Chinese", "Snacks"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 2,
        slugs: {
          restaurant: "chinese-hut-greater-kailash-2-greater-kailash-2",
          city: "delhi",
        },
        cityState: "4",
        address:
          "A-104, Block A, Dayanand Colony, Lajpat Nagar, New Delhi, Delhi 110024, India",
        locality: "A Block",
        parentId: 61788,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "449339",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 2,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "62721",
        name: "Burger Singh (Big Punjabi Burgers)",
        uuid: "e9558355-20db-4726-8cf1-42c5bc72c15a",
        city: "4",
        area: "Kalkaji",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "v5uqzbstycxon0gvwghx",
        cuisines: [
          "Snacks",
          "Fast Food",
          "Indian",
          "American",
          "Beverages",
          "Desserts",
          "Mughlai",
          "North Indian",
          "Biryani",
          "Tibetan",
          "Chinese",
          "Continental",
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 2.5,
        slugs: {
          restaurant: "burger-singh-kalkaji-greater-kailash-2",
          city: "delhi",
        },
        cityState: "4",
        address: "B-91, 1st Floor, Kalkaji Main Road, New Delhi (South) - 110019",
        locality: "Kalkaji Main Road",
        parentId: 375065,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "62721",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 2.5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "506380",
        name: "Ghee and Turmeric",
        uuid: "10fd06bb-7eb0-4295-adc8-b851ae0c605f",
        city: "4",
        area: "South Extension 1",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "izvefzb96gaa8mffoexo",
        cuisines: [
          "North Indian",
          "Tandoor",
          "Punjabi",
          "Beverages",
          "Desserts",
          "Mughlai",
        ],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 4.800000190734863,
        slugs: {
          restaurant: "ghee-and-turmeric-south-ex-delhi-south-extension",
          city: "delhi",
        },
        cityState: "4",
        address:
          "Unit No. D-22, Ground Floor, South Extension Part-1, DEFENCE COLONY, South East, Delhi-110049",
        locality: "South Extension",
        parentId: 261287,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 5400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5400,
          message: "",
          title: "Delivery Charge",
          amount: "5400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6894693~p=13~eid=00000188-8cfe-0c45-015e-558100bd0d27",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "506380",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 4.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "475944",
        name: "Taste Of China",
        uuid: "318537c8-fa5f-42a3-aabb-a7629e8c96ba",
        city: "4",
        area: "East of Kailash",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "mgese2uvk9skssatyeo7",
        cuisines: ["Fast Food"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        slaString: "21 MINS",
        lastMileTravel: 0.699999988079071,
        slugs: {
          restaurant: "taste-of-china-greater-kailash-2-greater-kailash-2",
          city: "delhi",
        },
        cityState: "4",
        address:
          "D 8, 1st Floor, Near Wine Shop, DDA Market, East of Kailash, New Delhi",
        locality: "Raja Dhirsain Marg",
        parentId: 4306,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "475944",
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          lastMileTravel: 0.699999988079071,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "17518",
        name: "KFC",
        uuid: "8aa71b67-a19a-4ee1-ba37-5fd62e29be3e",
        city: "4",
        area: "Kalkaji",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
        cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 2,
        slugs: {
          restaurant: "kfc-f-4-kalkaji-greater-kailash-2",
          city: "delhi",
        },
        cityState: "4",
        address: "F-4, Kalka Ji, New Delhi",
        locality: "F Block",
        parentId: 547,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3800,
          message: "",
          title: "Delivery Charge",
          amount: "3800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "17518",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 2,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
  ];
  
export default resList;